### PR TITLE
Fix melspectrogram formula

### PR DESCRIPTION
**Pull request by Sergozh**
Hi there, 

I’ve made this pull request with the correction to the Mel spectrogram computing formula so that it conforms with the formula used in Librosa. 

Without this correction, the transformation results will differ. I’d be grateful if you could review my changes and respond as soon as possible. 

Thank you!

### CODE REVIEW

**Comment by dhrebeniuk** [comment]
@Sergozh , thanks for fix

**Comment by Sergozh** [comment]
@dhrebeniuk could you please update Pod file and include this change into framework? Thank you!

**Comment by dhrebeniuk** [comment]
@Sergozh , done

**Comment by Sergozh** [comment]
Great! Thanks!

**Pull request merged**
